const actionTypes = {
    "CAN_CASTLE" : "CAN_CASTLE",
    "CLEAR_CANDIDATE_MOVES" : "CLEAR_CANDIDATE_MOVES",
    "GENERATE_CANDIDATE_MOVES" : "GENERATE_CANDIDATE_MOVES",
    "NEW_MOVE" : "NEW_MOVE",
    "NEW_GAME" : "NEW_GAME",
    "PROMOTION_CLOSE" : "PROMOTION_CLOSE",
    "PROMOTION_OPEN" : "PROMOTION_OPEN",
    "STALEMATE" : "STALEMATE",
    "INSUFFICIENT_MATERIAL" : "INSUFFICIENT_MATERIAL",
    "WIN" : "WIN",
    "TAKE_BACK" : "TAKE_BACK",
    "TAKE_FORWARD":"TAKE_FORWARD",
    "SET_POSITION": 'SET_POSITION',
    "SET_PIECEPOSITION": 'SET_PIECEPOSITION',
    "PLAYERS_TURN": 'PLAYERS_TURN',
    "ONLINE_POSITION": 'ONLINE_POSITION',
    "CURRENT_INDEX": 'CURRENT_INDEX',
    "SET_PLAYERiD": 'SET_PLAYERiD',
     "UPDATE_GAME_STATE":"UPDATE_GAME_STATE",
  

}

export default actionTypes